// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0n0_CrtjtqTClXA-JvcjYZ-vlZcrGBuE',
    appId: '1:891403960585:web:45dc03cdbcf492261753d8',
    messagingSenderId: '891403960585',
    projectId: 'app-do-an-ae40f',
    authDomain: 'app-do-an-ae40f.firebaseapp.com',
    storageBucket: 'app-do-an-ae40f.firebasestorage.app',
    measurementId: 'G-EVREWRSZLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgP7Vl_h8HEnkxzFEL3HDhFWNYFVQ_Jws',
    appId: '1:891403960585:android:7dd6cef0c66dbf0e1753d8',
    messagingSenderId: '891403960585',
    projectId: 'app-do-an-ae40f',
    storageBucket: 'app-do-an-ae40f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIMZhuVHcGOhWby_CRBbGhRH1ZSU65UGQ',
    appId: '1:891403960585:ios:0930ca7d02f0d3851753d8',
    messagingSenderId: '891403960585',
    projectId: 'app-do-an-ae40f',
    storageBucket: 'app-do-an-ae40f.firebasestorage.app',
    iosBundleId: 'com.example.appDoAn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIMZhuVHcGOhWby_CRBbGhRH1ZSU65UGQ',
    appId: '1:891403960585:ios:0930ca7d02f0d3851753d8',
    messagingSenderId: '891403960585',
    projectId: 'app-do-an-ae40f',
    storageBucket: 'app-do-an-ae40f.firebasestorage.app',
    iosBundleId: 'com.example.appDoAn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0n0_CrtjtqTClXA-JvcjYZ-vlZcrGBuE',
    appId: '1:891403960585:web:ec24ea9c3793f53a1753d8',
    messagingSenderId: '891403960585',
    projectId: 'app-do-an-ae40f',
    authDomain: 'app-do-an-ae40f.firebaseapp.com',
    storageBucket: 'app-do-an-ae40f.firebasestorage.app',
    measurementId: 'G-DQYK1RDYRJ',
  );
}
